version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html/food-app
hooks:
  AfterInstall:
    - location: scripts/after_Install
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
