#!/bin/bash
cd /usr/share/nginx/html/food-app
sudo chmod -R 777 storage
sudo chmod -R 777 bootstrap/cache/
cd /usr/share/nginx/html/
sudo chown -R ec2-user:ec2-user food-app
cd food-app
composer update
rm -rf .env
cp .env.example .env
sed -i s/'APP_NAME=Laravel'/'APP_NAME="Food Delivery APP"'/g .env
sed -i s/'DB_PASSWORD='/'DB_PASSWORD=password'/g .env
sudo systemctl start mysqld.service
php artisan config:clear
php artisan key:generate
php artisan config:cache
php artisan migrate
php artisan db:seed
sudo systemctl stop mysqld.service
sudo chmod -R 777 storage/logs/